# 应用名称
spring:
  # 数据库配置
  datasource:
    # 数据源名称
    name: defaultDataSource
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/kola_permission?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  security:
    user:
      name: backbay2
      password: 123456
#      roles: ADMIN
  #是否启用开发属性默认值
  devtools:
    add-properties: true
  #解决报错Failed to start bean ‘documentationPluginsBootstrapper‘
  #原因:springboot2.6.0中将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #true:将显示请求参数和标头，这可能会导致潜在敏感数据的不安全日志记录
    #false:将屏蔽请求参数和标头，以防止潜在敏感数据的不安全日志记录
    log-request-details: true

# mybatis框架
#mybatis:
#  #MyBatis映射定位，指定Mybatis的Mapper文件
#  mapper-locations: classpath:mappers/*xml
#  #指定Mybatis的实体目录
#  type-aliases-package: com.backbay2.kolasecurity.domain

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    #配置日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


# 访问示例：http://localhost:9999/monitor
management:
  endpoints:
    web:
      # actuator的访问路径，替换默认/actuator
      base-path: /monitor
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # include: info,health,env,metrics,mappings  # 方式1: 暴露端点env，配置多个以,隔开
        include: "*"     # 方式2: 包括所有端点，注意需要添加引号
        # 排除端点
        exclude: shutdown
  server:
    port: 9999  #新开监控端口，不和应用用同一个端口
  endpoint:
    health:
      show-details: always # 显示db、redis、rabbit连接情况等
    shutdown:
      enabled: true  #默认情况下，除shutdown以外的所有端点均已启用。手动开启
#  access:
#    white-list:
#      - 127.0.0.1
    #禁用/env接口 示例
#    env:
#      enabled: false

#日志相关配置
logging:
  # 开启web相关的日志记录
  level:
    web: DEBUG
  config: classpath:logback/logback-dev.xml
# 配置了公钥和私钥的位置
rsa:
  key:
    pubKeyPath:  classpath:/keystore/rsa/id_key_rsa.pub
    priKeyPath: classpath:/keystore/rsa/id_key_rsa
